spring.application.name=repppp
spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.datasource.username=admin
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
