CREATE TABLE IF NOT EXISTS products (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name VARCHAR(100) NOT NULL,
                                        description VARCHAR(500) NOT NULL,
                                        price NUMERIC(19, 2) NOT NULL CHECK (price >= 0),
                                        image_url VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username VARCHAR(50) NOT NULL UNIQUE,
                                     password_hash VARCHAR(100) NOT NULL,
                                     reputation INT DEFAULT 0 NOT NULL
);

INSERT INTO products (name, description, price, image_url)
VALUES
    ('Black Hoodie', 'Basic black hoodie', 49.99, 'https://example.com/hoodie.jpg'),
    ('White T-Shirt', 'Classic white t-shirt', 19.99, 'https://example.com/tshirt.jpg');